server:
  port: 8081
  servlet:
    session:
      timeout: 30m
#debug: true
spring:
  profiles:
    active: prod
  pid:
    file: /var/log/app.pid
  web:
    resources:
      static-locations:
      - /home/ubuntu/static
      - classpath:/static
